[book]
authors = ["The AeroRust community <aerospace.rust@gmail.com>"]
language = "en"
multilingual = false
src = "drone-book"
title = "The Rust book for Drones"

[build]
build-dir = "drone-book/book"