version: '3.8'

services:
  px4-gazebo-headless:
    build: https://github.com/Aerorust/px4-gazebo-headless.git#main
    container_name: px4-gazebo-headless
    environment:
      VERBOSE: "1"
      VERBOSE_SIM: "1"
    ports:
      # for MAVLINK API/Offboard and MAVSDK
      - "14540-14549:14540-14549"
      # for MAVLINK QGroundControl
      - "14550:14550"
      # simulator
      - "4560:4560"
      # For Video Stream
      # try the RTSP port https://github.com/JonasVautherin/px4-gazebo-headless/blob/master/sitl_rtsp_proxy/main.cpp#L12
      - "8554:8554"
      # try default UDP Gazebo port https://dev.px4.io/master/en/simulation/gazebo.html#video-streaming
      - "5600:5600/udp"
      # default gazebo port for conecting with client
      - "11345:11345"
    networks:
      internal-ip:
          ipv4_address: 172.20.0.5
      internal:
      external:
    stdin_open: true
    tty: true
    # Video stream is only supported on `Typhoon H480` see https://dev.px4.io/master/en/simulation/gazebo.html#video-streaming
    # Proxy service from docker container using `H264`
    # Some of the options: typhoon_h480, iris, iris_opt_flow, solo
    command:  -w baylands -v typhoon_h480 172.20.0.6
  mavsdk-grpc-server:
    depends_on:
      - px4-gazebo-headless
    build:
      dockerfile: Dockerfile-server
      context: mav-sdk
    container_name: mavsdk-grpc-server
    # entrypoint: /server/mavsdk_server_manylinux2010-x64 -p 4000 udp://:14540
    ports:
      - "4000:4000"
    networks:
      internal-ip:
          ipv4_address: 172.20.0.6
      internal:
      external:
    stdin_open: true
    tty: true

networks:
  internal:
    internal: true
  external:
  internal-ip:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
