version: '3.8'

services:
  px4-gazebo-headless:
    platform: linux/amd64
    # image: jonasvautherin/px4-gazebo-headless:latest
    image: jonasvautherin/px4-gazebo-headless:1.11.0
    container_name: px4-gazebo-headless
    ports:
      # for MAVLINK API/Offboard and MAVSDK
      - "127.0.0.1:14540:14540"
      # for MAVLINK QGroundControl
      - "14550:14550"
      # For Video Stream
      # try the RTSP port https://github.com/JonasVautherin/px4-gazebo-headless/blob/master/sitl_rtsp_proxy/main.cpp#L12
      - "127.0.0.1:8554:8554/tcp"
      # try default UDP Gazebo port https://dev.px4.io/master/en/simulation/gazebo.html#video-streaming
      - "5600:5600/udp"
    networks:
      - internal
      - external
    stdin_open: true
    tty: true
    # Video stream is only supported on `Typhoon H480` see https://dev.px4.io/master/en/simulation/gazebo.html#video-streaming
    # Proxy service from docker container using `H264`
    command: -v typhoon_h480 -w baylands
  mavsdk-grpc-server:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile-server
      context: mav-sdk
    container_name: mavsdk-grpc-server
    # entrypoint: /server/mavsdk_server_manylinux2010-x64 -p 4000 udp://:14540
    ports:
      - "4000:4000"
    networks:
      - internal
      - external
    stdin_open: true
    tty: true

networks:
  internal:
    internal: true
  external:
  # To set a custom subnet for the IP addresses of the setup
  # otherwise just use `0.0.0.0`
  #   driver: bridge
  #   ipam:
  #     driver: default
  #     config:
  #     - subnet: 192.168.220.0/24
