FROM ubuntu:20.04

LABEL maintainer="aerospace.rust@gmail.com"

RUN  apt update \
  && apt install -y wget \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /server

# This is latest version from the time of writing this comment
# update accordingly, but also you're able to override this when building the image
ARG MAVSDK_VERSION=1.4.4

RUN /bin/bash -c 'set -ex && \
  ARCH=`uname -m` && \
  if [ "$ARCH" == "aarch64" ]; then \
  wget -O mavsdk_server https://github.com/mavlink/MAVSDK/releases/download/v${MAVSDK_VERSION}/mavsdk_server_linux-arm64-musl; \
  else \
  wget -O mavsdk_server https://github.com/mavlink/MAVSDK/releases/download/v${MAVSDK_VERSION}/mavsdk_server_manylinux2010-x64; \
  fi'

RUN chmod +x mavsdk_server

EXPOSE 4000

ENTRYPOINT ["/server/mavsdk_server", "-p", "4000"]

CMD ["udp://:14540"]
